version: '2'
services:
  database:
    image: mongo:latest
    restart: always
    container_name: "mongodb"
    environment:
       - MONGO_DATA_DIR=/data/db
       - MONGO_LOG_DIR=/dev/null
       - MONGODB_USER=haad
       - MONGODB_PASS=12345
    volumes:
       - ./data-mongo/db:/data/db
    expose:
       - 27010-27012
  portfolio:
    build:
       context: ./portfolio
    depends_on:
       - database
       - controller
  controller:
    build:
       context: ./stock_controller
    environment:
       - PYTHONPATH=/src/
